spring.mvc.log-request-details = true
spring.main.log-startup-info = true
spring.application.admin.enabled = true

logging.file.name = mylog.log
logging.group.dev = com.socialapp.main.MainController, UnsecuredFilterLogger, mainLogger, \
com.socialapp.main.Security.AuthEventListener,  com.socialapp.main.Security.CheckUriFilter, \
com.socialapp.main.MainRepository, com.socialapp.main.Controllers.ProfileController, \
com.socialapp.main.Security.DatabaseRequestCache, com.socialapp.main.Services.UserService, \
com.socialapp.main.Controllers.MyErrorController, com.socialapp.main.Controllers.ChannelController, \
com.socialapp.main.Security.Acl.MyPermissionGrantingStrategy, \
com.socialapp.main.Security.AuthenticationEventListener, \
com.socialapp.main.Security.AuthorizationEventListener

logging.level.dev = debug
logging.level.web = debug

spring.datasource.url=jdbc:postgresql://localhost/postgres?currentSchema=social_app
spring.datasource.username=test_1234
spring.datasource.password=1234

userfile.dir = src/main/resources/static/uploads/
userfile.minsize = 1
userfile.maxsize = 200000

spring.mvc.message-codes-resolver-format = POSTFIX_ERROR_CODE

debug= true

server.servlet.session.cookie.domain = localhost
server.servlet.session.cookie.max-age = 3600
server.servlet.session.cookie.name= socialappcookie
server.servlet.session.cookie.same-site = strict

spring.lifecycle.timeout-per-shutdown-phase = 5s
spring.jdbc.template.query-timeout = 10s
spring.cache.type = none

logging.level.org.springframework.security=debug

spring.security.user.name=test
spring.security.user.password=1234

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

webauthn.rp-name = SocialApp
webauthn.rp-id = localhost
webauthn.allowed-origins = http://localhost:8080/

server.servlet.session.timeout = 20m

